#! /bin/sh

if [ $1 = "dev" ]; then
  docker-compose -f ../build/docker-compose.dev.yml -p bookshelf_dev up -d
  exit 0
else
  docker-compose -f ../build/docker-compose.local.yml -p bookshelf_local up -d
  exit 0
fi
