name: CI (deploy)

on:
  release:
    types: [released]

jobs:
  audit:
    uses: ./.github/workflows/audit.yml
  deploy:
    needs: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy backend
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
        run: curl -v $DEPLOY_URL
